// @ts-check
const { test, expect } = require('@playwright/test');

// Runs only when a Pro asset override is active (appsettings.Local.json generated by
// tools\demo\Set-WaProAssets.ps1 from WA_PRO_DIST or WA_PRO_*_URL env vars) - the default
// free-CDN demo cannot upgrade Pro components, so the spec self-skips there.
// Guards the whole Pro delivery chain: config override -> WebAwesomeAssets absolutized tags ->
// autoloader base path -> Pro component upgrade. The absolutization matters: WA derives its
// component base path from the loader script's raw src attribute, and a relative value is a
// bare dynamic-import specifier that fails silently (components never upgrade).
test('Pro components upgrade when a Pro asset override is active', async ({ page, request }) => {
  const probe = await request.get('appsettings.Local.json');
  const contentType = probe.headers()['content-type'] ?? '';
  test.skip(!probe.ok() || !contentType.includes('json'), 'no Pro asset override active (free CDN mode)');

  await page.goto('/components/combobox');
  await page.waitForSelector('.demo-shell');

  await page.waitForFunction(() => !!customElements.get('wa-combobox'), null, { timeout: 15000 });

  // the rendered combobox exposes a shadow root once upgraded
  const hasShadow = await page.locator('wa-combobox').first().evaluate(el => !!el.shadowRoot);
  expect(hasShadow).toBe(true);
});
