*.suo
*.user
*.pdb
*.bak
*.log
*/bin
*/bin/*
*/obj
*/obj/*
*/pkg
*/pkg/*
*/pkgobj
*/pkgobj/*
*/.SatelliteAssemblies
*/.SatelliteAssemblies/*
*/packages
*/packages/*
*/.vs
*/.vs/*
*/.idea
*/.idea/*
*/output
*/output/*
/.claude/settings.local.json
*/temp
*/temp/*
*/TestResults
*/TestResults/*