*.suo
*.user
*.pdb
*.bak
*.log
*/bin
*/bin/*
*/obj
*/obj/*
*/pkg
*/pkg/*
*/pkgobj
*/pkgobj/*
*/.SatelliteAssemblies
*/.SatelliteAssemblies/*
*/packages
*/packages/*
*/.vs
*/.vs/*
*/.idea
*/.idea/*
*/output
*/output/*
/.claude/settings.local.json
*/temp
*/temp/*
*/TestResults
*/TestResults/*
*.patch
*/node_modules
*/node_modules/*
*/playwright-report
*/playwright-report/*
*/test-results
*/test-results/*
appsettings.Local.json
/src/WebAwesome.Blazor.Demo/wwwroot/webawesome
/src/WebAwesome.Blazor.Demo/wwwroot/webawesome/*
