using System;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using WebAwesome.Blazor.Extensions;
using WebAwesome.Blazor.Demo.Services;

namespace WebAwesome.Blazor.Demo;

/// <summary>
/// Entry point of the Web Awesome Blazor demo application.
/// </summary>
public static class Program
{
    /// <summary>
    /// Configures and runs the WebAssembly host.
    /// </summary>
    /// <param name="args">Command line arguments</param>
    public static async Task Main(string[] args)
    {
        var builder = WebAssemblyHostBuilder.CreateDefault(args);
        builder.RootComponents.Add<App>("#app");
        builder.RootComponents.Add<HeadOutlet>("head::after");

        // optional, never-committed local override (Pro CDN/kit URL or self-hosted Pro dist);
        // generated by tools\demo\Set-WaProAssets.ps1 and ignored by version control
        await LoadLocalSettingsAsync(builder);

        builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });
        builder.Services.AddScoped<ApiSurfaceService>();

        // the getting-started path consumers follow: services + configuration binding
        builder.Services.AddWebAwesome(builder.Configuration);

        await builder.Build().RunAsync();
    }

    #region ------ Internals ------

    private static async Task LoadLocalSettingsAsync(WebAssemblyHostBuilder builder)
    {
        using var http = new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) };
        try
        {
            using var response = await http.GetAsync("appsettings.Local.json");

            // hosts with SPA fallback answer 200 with HTML for missing files - only accept real JSON
            if (!response.IsSuccessStatusCode) return;
            var mediaType = response.Content.Headers.ContentType?.MediaType;
            if (mediaType is not null && !mediaType.Contains("json", StringComparison.OrdinalIgnoreCase)) return;

            using var stream = await response.Content.ReadAsStreamAsync();
            builder.Configuration.AddJsonStream(stream);
        }
        catch (HttpRequestException)
        {
            // no local override present
        }
    }

    #endregion
}
