name: build-and-pack

on:
  push:
    branches: [ "main", "release-**" ]
    tags: [ "wa-blazor-*" ]
  pull_request:
    branches: [ "main", "release-**" ]
  workflow_dispatch:

defaults:
  run:
    working-directory: src

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
            10.0.x

      - name: Restore
        run: dotnet restore WebAwesome.slnx /p:Configuration=Release

      - name: Build and pack
        run: dotnet build WebAwesome.slnx --no-restore /p:Configuration=Release

      # Determine version:
      # - If this is a tag 'wa-blazor-*', use the tag value after the slash
      # - Otherwise, let csproj/Directory.Build.props decide (or generate a CI suffix)
      #- name: Compute version (if tagged)
      #  id: meta
      #  shell: pwsh
      #  run: |
      #    $ref = "${{ github.ref }}"
      #    if ($ref -like "refs/tags/wa-blazor-*") {
      #      $ver = $ref.Substring("refs/tags/wa-blazor-".Length)
      #      echo "version=$ver" >> $env:GITHUB_OUTPUT
      #    }

      #- name: Pack
      #  run: |
      #    if ("${{ steps.meta.outputs.version }}" -ne "") {
      #      dotnet pack WebAwesome.slnx --no-build /p:Configuration=Release /p:ContinuousIntegrationBuild=true /p:Version=${{ steps.meta.outputs.version }}
      #    } else {
      #      dotnet pack WebAwesome.slnx --no-build /p:Configuration=Release /p:ContinuousIntegrationBuild=true
      #    }

      # Note a step that "uses" ignores the default working directory
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: nupkg
          path: src/output/packages/Release/*.nupkg
          if-no-files-found: error
          overwrite: true

